### ISSUE TITLE
Not an Issue just a request

### ISSUE THREAD

**Issue by Neil-J17** [mokhin-denis/mod_myanniversary#2]
Great module, is there anyway to display the article rather than the link to it? I would like to use the module to have an "on this day" article on the home page.

Kind Regards
Neil

**Comment by mokhin-denis** [comment]
Thanx for your request. I'll think about it and try to do this.

**Comment by mokhin-denis** [comment]
By editing your Joomla template you can set the module layout as you wish. There is enough functionality for your requested feature.  You just need little PHP knowledge
